export const REQUEST_PENDING = "MOVIES::REQUEST_PENDING";
export const REQUEST_SUCCESS = "MOVIES::REQUEST_SUCCESS";
export const REQUEST_ERROR = "MOVIES::REQUEST_ERROR";
export const MAP_MOVIE_DATA = "MOVIES::MAP_DATA";