export const PROFILE_CHANGE_AVATAR = "PROFILE::CHANGE_AVATAR";
export const PROFILE_SET_AUTH = "PROFILE::SET_AUTH";
export const PROFILE_SET_ERROR = "PROFILE::SET_ERROR";
export const PROFILE_DROP_NAME = "PROFILE::DROP_NAME";
export const PROFILE_SET_NAME = "PROFILE::SET_NAME";
export const PROFILE_TOGGLE_SHOW = "PROFILE::TOGGLE_SHOW";